fragment Comment on Comment {
  id
  post {
    id
  }
  content
  deleted
  level
  createdAt
  updatedAt
  author {
    id
    username
  }
  parentComment {
    id
  }
  score {
    score
  }
  netVotes
  userVote {
    direction
  }
}

mutation createComment($input: createCommentInput!) {
  createComment(input: $input) {
    ...Comment
  }
}

mutation updateComment($input: updateCommentInput!) {
  updateComment(input: $input) {
    ...Comment
  }
}

mutation deleteComment($input: deleteCommentInput!) {
  deleteComment(input: $input) {
    ...Comment
  }
}
