fragment Comment on Comment {
  id
  postId
  content
  deleted
  level
  createdAt
  updatedAt
  authorId
  parentCommentId
  score
  netVotes
  userVote {
    direction
  }
}

mutation createComment($input: createCommentInput) {
  createComment(input: $input) {
    ...Comment
  }
}

mutation updateComment($input: updateCommentInput) {
  updateComment(input: $input) {
    ...Comment
  }
}

mutation deleteComment($id: ID) {
  deleteComment(id: $id) {
    ...Comment
  }
}
