fragment Post on Post {
  id
  title
  link
  content
  deleted
  createdAt
  updatedAt
  authorId
  commentCount
  netVotes
  score
  userVote {
    direction
  }
}

query GetPosts($sort: Sort) {
  getPosts(sort: $sort) {
    ...Post
  }
}

query GetPostById($id: ID, $commentSort: CommentSort) {
  getPostById(id: $id) {
    ...Post
    comments(commentSort: $commentSort) {
      ...Comment
    }
  }
}

mutation createPost($input: createPostInput) {
  createPost(input: $input) {
    ...Post
  }
}

mutation updatePost($input: updatePostInput) {
  updatePost(input: $input) {
    ...Post
  }
}

mutation deletePost($id: ID) {
  deletePost(id: $id) {
    ...Post
  }
}
