fragment PostStub on Post {
  id
  title
  link
  deleted
  createdAt
  updatedAt
  author {
    id
    username
  }
  commentCount
  netVotes
  score {
    score
  }
  userVote {
    direction
  }
}

fragment PostDetail on Post {
  ...PostStub
  content
  comments {
    ...Comment
  }
}

query Posts($sort: PostSort, $offset: Int) {
  posts(sort: $sort, offset: $offset) {
    ...PostStub
  }
}

query Post($id: String!) {
  post(id: $id) {
    ...PostDetail
  }
}

mutation createPost($input: createPostInput!) {
  createPost(input: $input) {
    ...PostStub
    content
  }
}

mutation updatePost($input: updatePostInput!) {
  updatePost(input: $input) {
    ...PostStub
    content
  }
}

mutation deletePost($input: deletePostInput!) {
  deletePost(input: $input) {
    ...PostStub
  }
}
