query getUser($id: ID) {
  getUser(id: $id) {
    id
    posts {
      ...Post
    }
    comments {
      ...Comment
      post {
        ...Post
      }
    }
  }
}

mutation createUserPostVote($input: createUserPostVoteInput!) {
  createUserPostVote(input: $input) {
    ...Post
  }
}

mutation deleteUserPostVote($postId: ID) {
  deleteUserPostVote(postId: $postId) {
    ...Post
  }
}

mutation createUserCommentVote($input: createUserCommentVoteInput!) {
  createUserCommentVote(input: $input) {
    ...Comment
  }
}

mutation deleteUserCommentVote($commentId: ID) {
  deleteUserCommentVote(commentId: $commentId) {
    ...Comment
  }
}

mutation setUsername($username: String) {
  setUsername(username: $username)
}
