query User($id: String!) {
  user(id: $id) {
    id
    username
    posts {
      ...PostDetail
    }
    comments {
      ...Comment
      post {
        ...PostStub
      }
    }
  }
}

mutation createUserPostVote($input: createUserPostVoteInput!) {
  createUserPostVote(input: $input) {
    post {
      id
      netVotes
      userVote {
        direction
      }
    }
  }
}

mutation deleteUserPostVote($input: deleteUserPostVoteInput!) {
  deleteUserPostVote(input: $input) {
    post {
      id
      netVotes
      userVote {
        direction
      }
    }
  }
}

mutation createUserCommentVote($input: createUserCommentVoteInput!) {
  createUserCommentVote(input: $input) {
    comment {
      id
      netVotes
      userVote {
        direction
      }
    }
  }
}

mutation deleteUserCommentVote($input: deleteUserCommentVoteInput!) {
  deleteUserCommentVote(input: $input) {
    comment {
      id
      netVotes
      userVote {
        direction
      }
    }
  }
}

mutation setUsername($input: setUsernameInput!) {
  setUsername(input: $input) {
    id
    username
  }
}
